const imagePool = [
  'https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=900&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=900&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=900&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=900&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=900&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1562967916-eb82221dfb92?w=900&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=900&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=900&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=900&auto=format&fit=crop',
  'https://images.pexels.com/photos/262959/pexels-photo-262959.jpeg?auto=compress&cs=tinysrgb&w=900',
  'https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?w=900&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=900&auto=format&fit=crop',
];

const biryaniImagePool = [
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f2/Biryani_chicken.jpg/960px-Biryani_chicken.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/23/A_home_made_plate_of_mutton_biryani_served_with_chicken_kassa_cooked_in_the_bengali_style.jpg/960px-A_home_made_plate_of_mutton_biryani_served_with_chicken_kassa_cooked_in_the_bengali_style.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/16/Egg_Biryani_in_a_restaurant.jpg/960px-Egg_Biryani_in_a_restaurant.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c8/Biryani_1.jpg/960px-Biryani_1.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/09/Vegetable_Biryani_IMG_001.jpg/960px-Vegetable_Biryani_IMG_001.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dd/Biryani_from_Tamilnadu.jpg/960px-Biryani_from_Tamilnadu.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a5/Biryani_from_Tamilnadu_2.jpg/960px-Biryani_from_Tamilnadu_2.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5a/%22Hyderabadi_Dum_Biryani%22.jpg/960px-%22Hyderabadi_Dum_Biryani%22.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/60/Biryani_2.jpg/960px-Biryani_2.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/72/Chicken_Biryani_with_Banana_and_Salad.jpg/960px-Chicken_Biryani_with_Banana_and_Salad.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/54/Biryani_from_kolkata.jpg/960px-Biryani_from_kolkata.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Biryani_from_Kolkata_2.jpg/960px-Biryani_from_Kolkata_2.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/51/Biryani_ready_to_serve.JPG/960px-Biryani_ready_to_serve.JPG',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7b/Biryani_rice.JPG/960px-Biryani_rice.JPG',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5f/Shrimp_Biriyani.JPG/960px-Shrimp_Biriyani.JPG',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c9/Biryani_with_chicken.jpg/960px-Biryani_with_chicken.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/38/Chicken_Dum_Biryani_03.jpg/960px-Chicken_Dum_Biryani_03.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/38/Dum_Biryani_Plate.jpg/960px-Dum_Biryani_Plate.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5d/Biryani_Kebab_onionsF.jpg/960px-Biryani_Kebab_onionsF.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f0/Biryani_Kebab_vegiesD.jpg/960px-Biryani_Kebab_vegiesD.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b1/Biryani_in_Hyderabad.jpg/960px-Biryani_in_Hyderabad.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7d/Biryani_in_khartoum.JPG/960px-Biryani_in_khartoum.JPG',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ac/Biryani_lahore.jpg/960px-Biryani_lahore.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cf/Biryani_of_Lahore.jpg/960px-Biryani_of_Lahore.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/eb/Biryani_rice_3.JPG/960px-Biryani_rice_3.JPG',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/14/Biryani_BY_Fatima.jpg/960px-Biryani_BY_Fatima.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/48/Biryani_By_Fatima.jpg/960px-Biryani_By_Fatima.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8d/Kacchi_Biryani_with_Jali_Kabab.jpg/960px-Kacchi_Biryani_with_Jali_Kabab.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3a/Kacchi_Biryani_01.jpg/960px-Kacchi_Biryani_01.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c4/Kacchi_Biryani_04.jpg/960px-Kacchi_Biryani_04.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7b/Kacchi_Biryani_Homemade.jpg/960px-Kacchi_Biryani_Homemade.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/Kacchi_Biryani_and_Borhani.jpg/960px-Kacchi_Biryani_and_Borhani.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/85/Lahori_Biryani%2C_Folk_Cuisine_of_Pakistan.jpg/960px-Lahori_Biryani%2C_Folk_Cuisine_of_Pakistan.jpg',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ed/Lamb_Biryani_-_Biryani_House_AUD8.50_%283643374430%29.jpg/960px-Lamb_Biryani_-_Biryani_House_AUD8.50_%283643374430%29.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/1/1e/Biryani_Raita.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f5/Biryani_Rice.jpg/960px-Biryani_Rice.jpg',
];

// Correct per-item image URLs for desserts
const dessertImageMap = {
  'Gulab Jamun': 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=900&auto=format&fit=crop',
  'Rasgulla': 'https://images.unsplash.com/photo-1666513506614-9dd4e95be025?w=900&auto=format&fit=crop',
  'Rasmalai': 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=900&auto=format&fit=crop',
  'Jalebi': 'https://images.unsplash.com/photo-1666513505896-65f7af5cbb29?w=900&auto=format&fit=crop',
  'Kaju Katli': 'https://images.pexels.com/photos/9843584/pexels-photo-9843584.jpeg?auto=compress&cs=tinysrgb&w=900',
  'Mysore Pak': 'https://images.pexels.com/photos/9843611/pexels-photo-9843611.jpeg?auto=compress&cs=tinysrgb&w=900',
  'Badam Halwa': 'https://images.pexels.com/photos/15417447/pexels-photo-15417447.jpeg?auto=compress&cs=tinysrgb&w=900',
  'Carrot Halwa': 'https://images.unsplash.com/photo-1666513506010-e4c5f3e27862?w=900&auto=format&fit=crop',
  'Wheat Halwa': 'https://images.pexels.com/photos/15417447/pexels-photo-15417447.jpeg?auto=compress&cs=tinysrgb&w=900',
  'Sooji Halwa': 'https://images.pexels.com/photos/15417447/pexels-photo-15417447.jpeg?auto=compress&cs=tinysrgb&w=900',
  'Moong Dal Halwa': 'https://images.pexels.com/photos/15417447/pexels-photo-15417447.jpeg?auto=compress&cs=tinysrgb&w=900',
  'Gajar Halwa': 'https://images.unsplash.com/photo-1666513506010-e4c5f3e27862?w=900&auto=format&fit=crop',
  'Kulfi': 'https://images.unsplash.com/photo-1567171466295-4afa63d45416?w=900&auto=format&fit=crop',
  'Malai Kulfi': 'https://images.unsplash.com/photo-1567171466295-4afa63d45416?w=900&auto=format&fit=crop',
  'Pista Kulfi': 'https://images.unsplash.com/photo-1567171466295-4afa63d45416?w=900&auto=format&fit=crop',
  'Mango Kulfi': 'https://images.pexels.com/photos/1346347/pexels-photo-1346347.jpeg?auto=compress&cs=tinysrgb&w=900',
  'Falooda': 'https://images.unsplash.com/photo-1617196034438-e5c2bdbb7cc4?w=900&auto=format&fit=crop',
  'Royal Falooda': 'https://images.unsplash.com/photo-1617196034438-e5c2bdbb7cc4?w=900&auto=format&fit=crop',
  'Fruit Falooda': 'https://images.unsplash.com/photo-1617196034438-e5c2bdbb7cc4?w=900&auto=format&fit=crop',
  'Mango Falooda': 'https://images.unsplash.com/photo-1617196034438-e5c2bdbb7cc4?w=900&auto=format&fit=crop',
  'Fruit Salad': 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=900&auto=format&fit=crop',
  'Fruit Custard': 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=900&auto=format&fit=crop',
  'Caramel Custard': 'https://images.unsplash.com/photo-1557499305-87a9d14741bd?w=900&auto=format&fit=crop',
  'Chocolate Brownie': 'https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=900&auto=format&fit=crop',
  'Walnut Brownie': 'https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=900&auto=format&fit=crop',
  'Chocolate Lava Cake': 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=900&auto=format&fit=crop',
  'Chocolate Cake': 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=900&auto=format&fit=crop',
  'Black Forest Cake': 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=900&auto=format&fit=crop',
  'Red Velvet Cake': 'https://images.unsplash.com/photo-1562440499-64c9a111f713?w=900&auto=format&fit=crop',
  'Pineapple Cake': 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=900&auto=format&fit=crop',
  'Vanilla Cake': 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&auto=format&fit=crop',
  'Cheesecake': 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=900&auto=format&fit=crop',
  'Blueberry Cheesecake': 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=900&auto=format&fit=crop',
  'Chocolate Mousse': 'https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?w=900&auto=format&fit=crop',
  'Mango Mousse': 'https://images.pexels.com/photos/1346347/pexels-photo-1346347.jpeg?auto=compress&cs=tinysrgb&w=900',
  'Tiramisu': 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=900&auto=format&fit=crop',
  'Ice Cream Sundae': 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=900&auto=format&fit=crop',
  'Chocolate Sundae': 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=900&auto=format&fit=crop',
  'Brownie Sundae': 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=900&auto=format&fit=crop',
  'Vanilla Ice Cream': 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=900&auto=format&fit=crop',
  'Chocolate Ice Cream': 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=900&auto=format&fit=crop',
  'Strawberry Ice Cream': 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=900&auto=format&fit=crop',
  'Butterscotch Ice Cream': 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=900&auto=format&fit=crop',
  'Mango Ice Cream': 'https://images.pexels.com/photos/1346347/pexels-photo-1346347.jpeg?auto=compress&cs=tinysrgb&w=900',
  'Pista Ice Cream': 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=900&auto=format&fit=crop',
  'Tender Coconut Ice Cream': 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=900&auto=format&fit=crop',
  'Rasmalai Cake': 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=900&auto=format&fit=crop',
  'Donut': 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=900&auto=format&fit=crop',
  'Chocolate Donut': 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=900&auto=format&fit=crop',
  'Choco Chip Cookie': 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=900&auto=format&fit=crop',
};

// Accurate descriptions for each dessert
const dessertDescMap = {
  'Gulab Jamun': 'Soft milk-solid dumplings soaked in fragrant rose-flavored sugar syrup.',
  'Rasgulla': 'Spongy cottage cheese balls simmered in light sugar syrup, served chilled.',
  'Rasmalai': 'Soft cottage cheese patties soaked in chilled saffron-infused sweet milk.',
  'Jalebi': 'Crispy deep-fried spirals soaked in warm fragrant saffron sugar syrup.',
  'Kaju Katli': 'Smooth melt-in-mouth cashew fudge garnished with silver leaf.',
  'Mysore Pak': 'Rich gram flour fudge cooked in ghee and sugar, a Karnataka specialty.',
  'Badam Halwa': 'Velvety almond halwa cooked in ghee with cardamom and saffron.',
  'Carrot Halwa': 'Classic gajar halwa made with grated carrots, full cream milk and ghee.',
  'Wheat Halwa': 'Silky smooth halwa made from whole wheat flour and clarified butter.',
  'Sooji Halwa': 'Fluffy semolina pudding cooked with ghee, sugar and dry fruits.',
  'Moong Dal Halwa': 'Rich slow-cooked split green gram halwa with ghee and cardamom.',
  'Gajar Halwa': 'Sweet carrot pudding slow-cooked with milk, sugar and cardamom.',
  'Kulfi': 'Dense creamy Indian ice cream with a rich nutty flavor, served on a stick.',
  'Malai Kulfi': 'Creamy kulfi made from reduced whole milk with fragrant cardamom.',
  'Pista Kulfi': 'Rich kulfi loaded with pistachios and flavored with rose water.',
  'Mango Kulfi': 'Refreshing kulfi made with Alphonso mango pulp and full cream.',
  'Falooda': 'Persian-origin dessert drink with vermicelli, basil seeds and rose syrup.',
  'Royal Falooda': 'Indulgent falooda topped with kulfi, dry fruits and extra ice cream.',
  'Fruit Falooda': 'Chilled falooda loaded with assorted fresh seasonal fruits.',
  'Mango Falooda': 'Falooda made with fresh mango pulp, vermicelli and sweet basil seeds.',
  'Fruit Salad': 'Fresh seasonal fruits tossed with a hint of honey and lemon.',
  'Fruit Custard': 'Chilled vanilla custard loaded with assorted fresh cut fruits.',
  'Caramel Custard': 'Silky baked egg custard with a golden caramel sauce on top.',
  'Chocolate Brownie': 'Dense fudgy chocolate brownie with a perfectly crispy crust.',
  'Walnut Brownie': 'Rich chocolate brownie studded with crunchy walnut pieces throughout.',
  'Chocolate Lava Cake': 'Warm chocolate cake with a gooey molten chocolate lava center.',
  'Chocolate Cake': 'Moist layered chocolate sponge cake with rich chocolate frosting.',
  'Black Forest Cake': 'Classic chocolate sponge layered with cherry compote and whipped cream.',
  'Red Velvet Cake': 'Vibrant red velvet sponge with smooth cream cheese frosting.',
  'Pineapple Cake': 'Light sponge layered with fresh pineapple chunks and whipped cream.',
  'Vanilla Cake': 'Soft fluffy vanilla sponge with clouds of creamy buttercream frosting.',
  'Cheesecake': 'Classic baked cheesecake with a buttery graham cracker crust.',
  'Blueberry Cheesecake': 'Creamy cheesecake topped with tangy-sweet blueberry compote.',
  'Chocolate Mousse': 'Light airy whipped chocolate mousse served chilled in a glass.',
  'Mango Mousse': 'Chilled airy mousse made with fresh Alphonso mango puree.',
  'Tiramisu': 'Classic Italian dessert with espresso-soaked ladyfingers and mascarpone.',
  'Ice Cream Sundae': 'Scoops of ice cream drizzled with caramel sauce, nuts and cherry.',
  'Chocolate Sundae': 'Chocolate ice cream topped with hot fudge sauce and whipped cream.',
  'Brownie Sundae': 'Warm fudgy brownie served with a generous scoop of vanilla ice cream.',
  'Vanilla Ice Cream': 'Classic creamy vanilla ice cream made with real vanilla bean extract.',
  'Chocolate Ice Cream': 'Rich dark chocolate ice cream with an intense cocoa flavor.',
  'Strawberry Ice Cream': 'Creamy strawberry ice cream made with real strawberry puree.',
  'Butterscotch Ice Cream': 'Smooth butterscotch-flavored ice cream with caramel ripple swirls.',
  'Mango Ice Cream': 'Refreshing mango ice cream bursting with tropical Alphonso mango flavor.',
  'Pista Ice Cream': 'Creamy pistachio ice cream with real pista chunks and rose water.',
  'Tender Coconut Ice Cream': 'Refreshing ice cream made with fresh tender coconut water and flesh.',
  'Rasmalai Cake': 'Fusion cake inspired by rasmalai, layered with saffron cream and cardamom.',
  'Donut': 'Classic ring-shaped donut with a sweet glazed sugar coating.',
  'Chocolate Donut': 'Soft fluffy donut dipped in a smooth rich chocolate glaze.',
  'Choco Chip Cookie': 'Buttery golden cookie loaded with generous dark chocolate chips.',
};

// Accurate descriptions for each Chinese item
const chineseDescMap = {
  'Veg Fried Rice': 'Classic wok-tossed rice with finely chopped seasonal vegetables.',
  'Chicken Fried Rice': 'Wok-tossed rice with tender chicken chunks and vegetables.',
  'Egg Fried Rice': 'Flavorful fried rice tossed with scrambled eggs and soy sauce.',
  'Schezwan Fried Rice': 'Spicy fried rice tossed in fiery home-made Schezwan sauce.',
  'Chicken Schezwan Fried Rice': 'Spicy Schezwan fried rice loaded with tender chicken pieces.',
  'Veg Schezwan Fried Rice': 'Perfectly cooked rice tossed with veggies in spicy Schezwan sauce.',
  'Mushroom Fried Rice': 'Savory fried rice tossed with fresh mushrooms and garlic.',
  'Paneer Fried Rice': 'Delicious fried rice mixed with soft paneer cubes and veggies.',
  'Mixed Fried Rice': 'Loaded fried rice with chicken, egg, prawns and vegetables.',
  'Singapore Fried Rice': 'Spicy, tangy and slightly sweet curry-flavored fried rice.',
  'Veg Hakka Noodles': 'Classic boiled noodles stir-fried with crunchy vegetables.',
  'Chicken Hakka Noodles': 'Stir-fried noodles with chicken strips, veggies and soy sauce.',
  'Egg Hakka Noodles': 'Wok-tossed noodles with scrambled eggs and fresh vegetables.',
  'Schezwan Noodles': 'Spicy stir-fried noodles tossed in fiery Schezwan sauce.',
  'Chicken Schezwan Noodles': 'Spicy Schezwan noodles loaded with chicken and veggies.',
  'Veg Chow Mein': 'Classic Indian-Chinese style stir-fried noodles with veggies.',
  'Chicken Chow Mein': 'Savory stir-fried noodles with chicken in a rich soy-based sauce.',
  'Singapore Noodles': 'Thin noodles stir-fried with veggies in a vibrant curry powder.',
  'Chilli Garlic Noodles': 'Spicy noodles tossed with burnt garlic and fiery chilli flakes.',
  'Veg Manchurian': 'Deep-fried vegetable balls in a spicy, sweet and tangy dark sauce.',
  'Chicken Manchurian': 'Fried chicken chunks tossed in a savory and tangy soy-garlic sauce.',
  'Gobi Manchurian': 'Crispy cauliflower florets tossed in a sweet and spicy sauce.',
  'Paneer Manchurian': 'Soft paneer cubes stir-fried in a tangy Indo-Chinese sauce.',
  'Chilli Chicken': 'Classic crispy chicken tossed in a spicy green chilli and soy sauce.',
  'Chilli Paneer': 'Crispy paneer cubes tossed with peppers in a spicy chilli sauce.',
  'Chilli Gobi': 'Crispy cauliflower tossed with peppers and onions in a spicy sauce.',
  'Dragon Chicken': 'Spicy red chicken strips tossed with cashew nuts and bell peppers.',
  'Garlic Chicken': 'Tender chicken tossed in a savory sauce with an intense garlic flavor.',
  'Hot Garlic Chicken': 'Chicken tossed in a spicy and pungent hot garlic sauce.',
  'Pepper Chicken': 'Spicy chicken stir-fry dominated by the bold flavor of black pepper.',
  'Honey Chicken': 'Crispy chicken pieces coated in a sweet, sticky honey glaze.',
  'Sweet and Sour Chicken': 'Fried chicken in a vibrant sweet and tangy sauce with pineapples.',
  'Crispy Chicken': 'Extra crunchy fried chicken strips tossed in a savory asian sauce.',
  'Crispy Corn': 'Spicy and crunchy deep-fried corn kernels tossed with peppers.',
  'Spring Rolls': 'Crispy golden rolls stuffed with savory mixed vegetables.',
  'Vegetable Spring Rolls': 'Golden fried rolls with a finely shredded vegetable filling.',
  'Chicken Spring Rolls': 'Crispy fried rolls filled with savory minced chicken and veggies.',
  'Chinese Bhel': 'Crispy fried noodles tossed with fresh veggies in Schezwan sauce.',
  'American Chopsuey': 'Crispy fried noodles topped with a sweet and tangy vegetable sauce.',
  'Chicken American Chopsuey': 'Crispy noodles topped with chicken in a sweet and tangy sauce.',
};

// Image map for Chinese items
const chineseImageMap = {
  'Veg Fried Rice': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=900&auto=format&fit=crop',
  'Chicken Fried Rice': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=900&auto=format&fit=crop',
  'Egg Fried Rice': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=900&auto=format&fit=crop',
  'Schezwan Fried Rice': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=900&auto=format&fit=crop',
  'Chicken Schezwan Fried Rice': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=900&auto=format&fit=crop',
  'Veg Schezwan Fried Rice': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=900&auto=format&fit=crop',
  'Mushroom Fried Rice': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=900&auto=format&fit=crop',
  'Paneer Fried Rice': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=900&auto=format&fit=crop',
  'Mixed Fried Rice': 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?w=900&auto=format&fit=crop',
  'Singapore Fried Rice': 'https://images.unsplash.com/photo-1562565652-a8e8f85f57dd?w=900&auto=format&fit=crop',
  'Veg Hakka Noodles': 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=900&auto=format&fit=crop',
  'Chicken Hakka Noodles': 'https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=900&auto=format&fit=crop',
  'Egg Hakka Noodles': 'https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=900&auto=format&fit=crop',
  'Schezwan Noodles': 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=900&auto=format&fit=crop',
  'Chicken Schezwan Noodles': 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=900&auto=format&fit=crop',
  'Veg Chow Mein': 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=900&auto=format&fit=crop',
  'Chicken Chow Mein': 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=900&auto=format&fit=crop',
  'Singapore Noodles': 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=900&auto=format&fit=crop',
  'Chilli Garlic Noodles': 'https://images.unsplash.com/photo-1552611052-3ba9d45c65fa?w=900&auto=format&fit=crop',
  'Veg Manchurian': 'https://images.unsplash.com/photo-1605335123908-41d1a6e9a9ef?w=900&auto=format&fit=crop',
  'Chicken Manchurian': 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=900&auto=format&fit=crop',
  'Gobi Manchurian': 'https://images.unsplash.com/photo-1615486171447-ad3cd5eefd7a?w=900&auto=format&fit=crop',
  'Paneer Manchurian': 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=900&auto=format&fit=crop',
  'Chilli Chicken': 'https://images.unsplash.com/photo-1525755673019-35de6fd41443?w=900&auto=format&fit=crop',
  'Chilli Paneer': 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=900&auto=format&fit=crop',
  'Chilli Gobi': 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=900&auto=format&fit=crop',
  'Dragon Chicken': 'https://images.unsplash.com/photo-1525755673019-35de6fd41443?w=900&auto=format&fit=crop',
  'Garlic Chicken': 'https://images.unsplash.com/photo-1623653387945-2fd256d475ce?w=900&auto=format&fit=crop',
  'Hot Garlic Chicken': 'https://images.unsplash.com/photo-1623653387945-2fd256d475ce?w=900&auto=format&fit=crop',
  'Pepper Chicken': 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=900&auto=format&fit=crop',
  'Honey Chicken': 'https://images.unsplash.com/photo-1525755673019-35de6fd41443?w=900&auto=format&fit=crop',
  'Sweet and Sour Chicken': 'https://images.unsplash.com/photo-1525755673019-35de6fd41443?w=900&auto=format&fit=crop',
  'Crispy Chicken': 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=900&auto=format&fit=crop',
  'Crispy Corn': 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=900&auto=format&fit=crop',
  'Spring Rolls': 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=900&auto=format&fit=crop',
  'Vegetable Spring Rolls': 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=900&auto=format&fit=crop',
  'Chicken Spring Rolls': 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=900&auto=format&fit=crop',
  'Chinese Bhel': 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=900&auto=format&fit=crop',
  'American Chopsuey': 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=900&auto=format&fit=crop',
  'Chicken American Chopsuey': 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=900&auto=format&fit=crop',
};

const categoryItems = {
  Biryani: [
    ['Chicken Biryani', 180], ['Mutton Biryani', 260], ['Egg Biryani', 140], ['Fish Biryani', 240],
    ['Vegetable Biryani', 150], ['Ambur Chicken Biryani', 220], ['Dindigul Chicken Biryani', 230],
    ['Hyderabadi Chicken Biryani', 240], ['Thalassery Biryani', 220], ['Donne Biryani', 210],
    ['Kolkata Chicken Biryani', 230], ['Malabar Chicken Biryani', 240], ['Mughlai Chicken Biryani', 250],
    ['Paneer Biryani', 170], ['Mushroom Biryani', 160], ['Prawn Biryani', 280],
    ['Chicken 65 Biryani', 220], ['Special Chicken Biryani', 300], ['Family Chicken Biryani', 420],
    ['Mini Chicken Biryani', 120],
    ['Hyderabadi Mutton Biryani', 300], ['Ambur Mutton Biryani', 280], ['Dindigul Mutton Biryani', 290],
    ['Thalappakatti Chicken Biryani', 260], ['Thalappakatti Mutton Biryani', 320],
    ['Chettinad Chicken Biryani', 250], ['Chettinad Mutton Biryani', 310], ['Malabar Mutton Biryani', 300],
    ['Kolkata Mutton Biryani', 290], ['Lucknowi Chicken Biryani', 260], ['Lucknowi Mutton Biryani', 320],
    ['Mughlai Mutton Biryani', 330], ['Tandoori Chicken Biryani', 280], ['Pepper Chicken Biryani', 250],
    ['Special Mutton Biryani', 360], ['Egg Chicken Biryani', 210],
  ],
  'South Indian': [
    ['Masala Dosa', 80], ['Plain Dosa', 65], ['Ghee Roast Dosa', 130], ['Onion Dosa', 95],
    ['Rava Dosa', 100], ['Onion Rava Dosa', 110], ['Podi Dosa', 90], ['Mysore Masala Dosa', 120],
    ['Set Dosa', 100], ['Neer Dosa', 95], ['Idli', 50], ['Kanchipuram Idli', 80],
    ['Podi Idli', 75], ['Mini Idli', 70], ['Idiyappam', 100], ['Appam', 90], ['Egg Appam', 130],
    ['Vegetable Uttapam', 110], ['Onion Uttapam', 105], ['Tomato Uttapam', 105], ['Podi Uttapam', 115],
    ['Ven Pongal', 95], ['Lemon Rice', 80], ['Tamarind Rice', 85], ['Curd Rice', 80],
    ['Tomato Rice', 85], ['Coconut Rice', 90], ['Vegetable Upma', 75], ['Rava Upma', 70], ['Medu Vada', 65],
  ],
  'North Indian': [
    ['Butter Chicken', 240], ['Kadai Chicken', 230], ['Chicken Tikka Masala', 250], ['Chicken Handi', 260],
    ['Chicken Do Pyaza', 240], ['Chicken Lababdar', 270], ['Chicken Korma', 260], ['Chicken Saagwala', 250],
    ['Chicken Rara', 280], ['Tandoori Chicken', 260], ['Chicken Tikka', 220], ['Malai Chicken Tikka', 240],
    ['Mutton Rogan Josh', 320], ['Mutton Korma', 330], ['Mutton Do Pyaza', 320], ['Mutton Handi', 340],
    ['Mutton Masala', 330], ['Mutton Keema', 300], ['Mutton Nihari', 350], ['Dal Makhani', 160],
    ['Dal Tadka', 120], ['Dal Fry', 110], ['Rajma Masala', 130], ['Chole Masala', 120],
    ['Paneer Butter Masala', 150], ['Kadai Paneer', 160], ['Shahi Paneer', 170], ['Palak Paneer', 155],
    ['Matar Paneer', 150], ['Paneer Tikka Masala', 190], ['Paneer Lababdar', 180], ['Malai Kofta', 180],
    ['Navratan Korma', 190], ['Aloo Gobi', 120], ['Aloo Matar', 120], ['Baingan Bharta', 130],
    ['Jeera Aloo', 110], ['Mix Vegetable Curry', 140], ['Vegetable Korma', 160], ['Dum Aloo', 150],
    ['Butter Naan', 50], ['Garlic Naan', 60], ['Plain Naan', 45], ['Tandoori Roti', 40],
    ['Missi Roti', 55], ['Lachha Paratha', 75], ['Aloo Paratha', 100], ['Paneer Paratha', 130],
    ['Amritsari Kulcha', 140], ['Stuffed Kulcha', 150],
  ],
  Pizza: [
    ['Margherita Pizza', 220], ['Farmhouse Pizza', 260], ['Veggie Supreme Pizza', 250], ['Paneer Tikka Pizza', 280],
    ['Corn Cheese Pizza', 230], ['Mushroom Pizza', 240], ['Chicken Tikka Pizza', 300], ['Chicken Pepperoni Pizza', 340],
    ['BBQ Chicken Pizza', 320], ['Chicken Supreme Pizza', 350],
  ],
  Beverages: [
    ['Masala Tea', 50], ['Ginger Tea', 55], ['Cardamom Tea', 60], ['Black Tea', 45], ['Green Tea', 60],
    ['Filter Coffee', 70], ['Cold Coffee', 120], ['Cappuccino', 140], ['Espresso', 100], ['Hot Chocolate', 150],
    ['Fresh Lime Soda', 80], ['Sweet Lime Juice', 90], ['Orange Juice', 100], ['Apple Juice', 110],
    ['Watermelon Juice', 90], ['Mango Juice', 100], ['Pineapple Juice', 110], ['Strawberry Milkshake', 160],
    ['Chocolate Milkshake', 160], ['Mango Milkshake', 150],
  ],
  Desserts: [
    ['Gulab Jamun', 80], ['Rasgulla', 90], ['Rasmalai', 150], ['Jalebi', 85], ['Kaju Katli', 200],
    ['Mysore Pak', 130], ['Badam Halwa', 160], ['Carrot Halwa', 120], ['Wheat Halwa', 100], ['Sooji Halwa', 80],
    ['Moong Dal Halwa', 140], ['Gajar Halwa', 120], ['Kulfi', 110], ['Malai Kulfi', 120], ['Pista Kulfi', 140],
    ['Mango Kulfi', 130], ['Falooda', 180], ['Royal Falooda', 220], ['Fruit Falooda', 190], ['Mango Falooda', 200],
    ['Fruit Salad', 110], ['Fruit Custard', 130], ['Caramel Custard', 140], ['Chocolate Brownie', 140],
    ['Walnut Brownie', 160], ['Chocolate Lava Cake', 220], ['Chocolate Cake', 180], ['Black Forest Cake', 220],
    ['Red Velvet Cake', 230], ['Pineapple Cake', 200], ['Vanilla Cake', 180], ['Cheesecake', 220],
    ['Blueberry Cheesecake', 250], ['Chocolate Mousse', 160], ['Mango Mousse', 150], ['Tiramisu', 280],
    ['Ice Cream Sundae', 160], ['Chocolate Sundae', 180], ['Brownie Sundae', 200], ['Vanilla Ice Cream', 100],
    ['Chocolate Ice Cream', 110], ['Strawberry Ice Cream', 110], ['Butterscotch Ice Cream', 110],
    ['Mango Ice Cream', 120], ['Pista Ice Cream', 130], ['Tender Coconut Ice Cream', 140],
    ['Rasmalai Cake', 260], ['Donut', 80], ['Chocolate Donut', 100], ['Choco Chip Cookie', 90],
  ],
  Chinese: [
    ['Veg Fried Rice', 140], ['Chicken Fried Rice', 180], ['Egg Fried Rice', 160], ['Schezwan Fried Rice', 170],
    ['Chicken Schezwan Fried Rice', 190], ['Veg Schezwan Fried Rice', 160], ['Mushroom Fried Rice', 170], ['Paneer Fried Rice', 180],
    ['Mixed Fried Rice', 210], ['Singapore Fried Rice', 200], ['Veg Hakka Noodles', 140], ['Chicken Hakka Noodles', 180],
    ['Egg Hakka Noodles', 160], ['Schezwan Noodles', 150], ['Chicken Schezwan Noodles', 190], ['Veg Chow Mein', 140],
    ['Chicken Chow Mein', 180], ['Singapore Noodles', 200], ['Chilli Garlic Noodles', 160], ['Veg Manchurian', 140],
    ['Chicken Manchurian', 210], ['Gobi Manchurian', 150], ['Paneer Manchurian', 180], ['Chilli Chicken', 220],
    ['Chilli Paneer', 180], ['Chilli Gobi', 150], ['Dragon Chicken', 240], ['Garlic Chicken', 230],
    ['Hot Garlic Chicken', 240], ['Pepper Chicken', 230], ['Honey Chicken', 240], ['Sweet and Sour Chicken', 230],
    ['Crispy Chicken', 250], ['Crispy Corn', 160], ['Spring Rolls', 130], ['Vegetable Spring Rolls', 130],
    ['Chicken Spring Rolls', 160], ['Chinese Bhel', 140], ['American Chopsuey', 190], ['Chicken American Chopsuey', 220],
  ],
  'Fast Food': [
    ['Veg Burger', 120], ['Chicken Burger', 160], ['Cheese Burger', 150], ['Paneer Burger', 150],
    ['French Fries', 100], ['Peri Peri Fries', 120], ['Chicken Nuggets', 170], ['Chicken Sandwich', 160],
    ['Veg Sandwich', 110], ['Grilled Sandwich', 140], ['Chicken Wrap', 180], ['Paneer Wrap', 160],
    ['Chicken Shawarma', 190], ['Veg Roll', 100], ['Chicken Roll', 150],
  ],
  Snacks: [
    ['Samosa', 40], ['Onion Pakoda', 60], ['Paneer Pakoda', 100], ['Chicken 65', 180], ['Chicken Wings', 220],
    ['French Fries', 100], ['Masala Vada', 45], ['Bajji', 50], ['Bonda', 45], ['Cutlet', 70],
    ['Corn', 80], ['Pani Puri', 70], ['Bhel Puri', 80], ['Masala Peanuts', 60], ['Spring Roll', 130],
  ],
};

let itemNumber = 1;
const additionalMenuItems = Object.entries(categoryItems).flatMap(([category, items]) => items.map(([name, price], index) => ({
  _id: `additional-${itemNumber++}`,
  restaurant: `r${(index % 3) + 1}`,
  name,
  category,
  description: category === 'Desserts' && dessertDescMap[name]
    ? dessertDescMap[name]
    : category === 'Chinese' && chineseDescMap[name]
      ? chineseDescMap[name]
      : `${name} prepared with fresh ingredients and traditional flavors.`,
  price,
  image: category === 'Biryani'
    ? `/biryani/${index + 1}.jpg`
    : category === 'South Indian'
      ? `/south-indian/${index + 1}.jpg`
      : category === 'North Indian'
        ? `/north-indian/${index + 1}.jpg`
        : category === 'Pizza'
          ? `/pizza/${index + 1}.jpg`
          : category === 'Beverages'
            ? `/beverages/${index + 1}.jpg`
            : category === 'Desserts' && dessertImageMap[name]
              ? dessertImageMap[name]
              : category === 'Chinese' && chineseImageMap[name]
                ? chineseImageMap[name]
                : category === 'Fast Food' && name === 'Paneer Burger'
                ? '/fast-food/paneer-burger.jpg'
                : category === 'Fast Food' && name === 'Paneer Wrap'
                  ? '/fast-food/paneer-wrap.jpg'
                  : category === 'Snacks' && name === 'Masala Vada'
                    ? '/snacks/masala-vada.jpg'
                    : category === 'Snacks' && name === 'Paneer Pakoda'
                      ? '/snacks/paneer-pakoda.jpg'
                      : imagePool[(itemNumber + index) % imagePool.length],
})));

module.exports = additionalMenuItems;
